#!/bin/sh

# Toggle floating dropdown terminal in i3, or start if non-existing.
# $1 is	the script run in the terminal.
# All other args are terminal settings.
# Terminal names are in dropdown_* to allow easily setting i3 settings.

[ -z "$1" ] && exit

if xwininfo -tree -root | grep "(\"dropdown_$1\" ";
then
	echo "Window detected."
	i3 "[instance=\"dropdown_$1\"] scratchpad show; [title=\"dropdown_$1\"] move position center"
else
	echo "Window not detected... spawning."
	i3-msg "exec st -n dropdown_$1 -e \"bc -lq\""
fi
