#!/usr/bin/env sh
# Give dmenu list of all unicode characters to copy.
# Shows the selected character in dunst if running.

if [ -e ~/scripts/fontawesome ]; then
    chosen=$(grep -v "#" -h ~/scripts/Emoji ~/scripts/fontawesome | rofi -dmenu -p 'Emoji' -i -l 18 -fn "NotoEmoji Nerd Font Complete Monospace-16")
fi

[ "$chosen" != "" ] || exit

c=$(echo "$chosen" | sed "s/ .*//")
echo "$c" | tr -d '\n' | xclip -selection clipboard
notify-send "'$c' copied to clipboard." &

s=$(echo "$chosen" | sed "s/.*; //" | awk '{print $1}')
echo "$s" | tr -d '\n' | xclip
notify-send "'$s' copied to primary." &

