#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send "Memory hogs" "$(ps axch -o cmd:15,%mem --sort=-%mem | head -n 12)" ;;
	3) notify-send "Memory module" "\- Shows Memory Used/Total.
- Click to show memory hogs." ;;
esac

free -h | awk '/^Mem:/ {print $3 "/" $2}'
