format = """
[ ](#87D7FF)\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$python\
$custom\
$cmd_duration\
$status\
$fill\
$time
$jobs\
$character"""

add_newline = false
continuation_prompt = "[❯](bold yellow) "

[fill]
symbol = " "

[cmd_duration]
min_time = 16
show_milliseconds = false
style = "yellow"

[directory]
truncation_length = 7
truncate_to_repo = false
truncation_symbol = ".../"
fish_style_pwd_dir_length = 2
style = "#00AFFF"
format = "[ ]($style) [$path]($style) [$read_only]($read_only_style)"

[git_branch]
symbol = "   "
style = "#5FD700"

[git_status]
style = "#5FD700"
ahead = "⇡$count "
behind = "⇣$count "
modified = "!$count "
staged = "+$count "
deleted = "-$count "
untracked = "?$count "
format = "[$ahead_behind]($style)[$deleted](#F10C0C)[$staged$modified](#D7AF00)[$untracked](#00AFFF)"

[python]
symbol = " "
style = "#00AFAF"

[status]
disabled = false
symbol = "✘ "
pipestatus = true
format = "[$symbol$common_meaning$signal_name$maybe_int]($style) "
pipestatus_format = "\\[$pipestatus\\] -> [$symbol$common_meaning$signal_name$maybe_int]($style)"

[time]
disabled = false
format = " [ $time]($style)"
style = "#5F8787"

