[manager]
ratio = [1, 5, 5]
sort_by = "natural"
sort_sensitive = true
# sort_translit = true
linemode = "size"
show_hidden = true
scrolloff = 4

[preview]
tabsize = 4
max_width = 850
max_height = 1000
cache_dir = "~/.cache/yazi"

