[manager]
ratio = [0, 5, 5]
sort_by = "natural"
sort_sensitive = true
# sort_translit = true
linemode = "size"
show_hidden = true
scrolloff = 4

[preview]
tabsize = 4
max_width = 926
max_height = 999
image_quality = 85
sixel_fraction = 10
image_delay = 25
cache_dir = "~/.cache/yazi"

# Plugins
[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

[[plugin.append_previewers]]
name = "*"
run = "hexyl"

[plugin]
prepend_previewers = [
	# Archive previewer
	{ mime = "application/*zip", run = "ouch" },
	{ mime = "application/x-tar", run = "ouch" },
	{ mime = "application/x-bzip2", run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar", run = "ouch" },
	{ mime = "application/x-xz", run = "ouch" },
	{ mime = "application/x-zstd-compressed-tar", run = "ouch" },
	{ mime = "application/zstd", run = "ouch" },
]

[opener]
play = [
	{ run = 'mpv --force-window "$@"', block = true, orphan = true },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info" }
]

