[manager]
ratio = [0, 5, 5]
sort_by = "natural"
sort_sensitive = true
# sort_translit = true
linemode = "size"
show_hidden = true
scrolloff = 4

[preview]
tabsize = 4
max_width = 939
max_height = 1000
image_quality = 85
sixel_fraction = 10
cache_dir = "~/.cache/yazi"

# Plugins
[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

