icons_format = "{icon}"

[theme]
theme = "plain"
[theme.overrides]
idle_bg = "#1E1E2E"
idle_fg = "#CDD6F4"
separator_fg = "#F5E0DC"
separator_bg = "#1E1E2E"
separator = " | "

[icons]
icons = "material-nf"

# MAYBE: Switch to the builtin "music" block
[[block]]
block = "custom"
interval = 12
command = "getsong"
format = " $text"
hide_when_empty = true
[block.theme_overrides]
idle_fg = "#3BFFB5"
[[block.click]]
button = "left"
cmd = "getsong 1"
update = true
[[block.click]]
button = "middle"
cmd = "getsong 2"
[[block.click]]
button = "right"
cmd = "getsong 3"
[[block.click]]
button = "up"
cmd = "getsong 4"
[[block.click]]
button = "down"
cmd = "getsong 5"

[[block]]
block = "memory"
format = "$icon $mem_used.eng(w:3,u:B,p:M)/$mem_total.eng(w:2,u:B,p:M)"
interval = 15
[[block.click]]
button = "left"
cmd = '''notify-send "Memory hogs" "$(ps axch -o cmd:15,%mem --sort=-%mem | head -n 13)"'''
update = true
[[block.click]]
button = ""
update = true

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 120
warning = 20.0
alert = 10.0
format = "$icon $available.eng(w:2)/$total"
[[block.click]]
button = "left"
update = true

[[block]]
block = "sound"
max_vol = 125
format = "$icon {$volume.eng(w:2)|}"
[[block.click]]
button = "left"
update = true
[[block.click]]
button = "right"
cmd = "pavucontrol"
[[block.click]]
button = "middle"
action = "toggle_mute"
[[block.click]]
button = "up"
action = "volume_down"
[[block.click]]
button = "down"
action = "volume_up"

# Temperature
[[block]]
block = "custom"
command = "cpu-heat"
format = "$text.pango-str()"
interval = 10
[[block.click]]
button = ""
update = true

# Battery
[[block]]
block = "custom"
command = "battery"
format = "$text.pango-str()"
interval = 15
[[block.click]]
button = "left"
cmd = "battery 1"
update = true

[[block]]
block = "time"
interval = 1
format = "$icon $timestamp.datetime(f:'%Y/%m/%d %H:%M:%S (%a)')"

