unstable_features = true
brace_style = "AlwaysNextLine"
comment_width = 100
control_brace_style = "AlwaysNextLine"
format_strings = true
hard_tabs = true
max_width = 101
normalize_comments = true
use_field_init_shorthand = true
wrap_comments = true
