#!/bin/bash
SCRIPT_FOLDER="$HOME/scripts"
SCRIPT_FILE="$SCRIPT_FOLDER/$1"
if [[ -f $SCRIPT_FILE ]]; then
	echo "File Already Exists"
else
	echo "#!/bin/bash" > "$SCRIPT_FILE"
	chmod +x "$SCRIPT_FILE"
	sudo ln -sf "$SCRIPT_FILE" "/usr/local/bin/$1"
fi

nvim "$SCRIPT_FILE"

