#!/bin/bash

START_COL="#FF0808"
END_COL="#08FF08"

PERC="$(acpi -b | awk '{print $4}' | sed s/,//)"
PERC_INT=${PERC//\%/}
[ "$(acpi -b | grep -i 'Discharging')" ] || DISC=" "

if   [ "$PERC_INT" -ge 90 ]; then SYMBOL="";
elif [ "$PERC_INT" -ge 75 ]; then SYMBOL="";
elif [ "$PERC_INT" -ge 50 ]; then SYMBOL="";
elif [ "$PERC_INT" -ge 25 ]; then SYMBOL="";
else SYMBOL=""; color="#FF0B0A"
fi

function clamp
{
	if [[ $1 -gt $3 ]] ; then
		clamped=$3
	elif [[ $1 -lt $2 ]] ; then
		clamped=$2
	else
		clamped=$1
	fi
}

# Arguments => "Current Percentage, Zero Percent Color ('#ABCDEF' format), Full Percentage Color"
function getColor {
	local r;
	local g;
	local b;
	local temp;
	local ratio;
	ratio=$(bc -l <<< "scale=2; $1/100")
	# Extract zero rgb and full rgb and convert to hex
	local rz=$(( 16#$(echo "$2" | cut -b2-3) ))
	local gz=$(( 16#$(echo "$2" | cut -b4-5) ))
	local bz=$(( 16#$(echo "$2" | cut -b6-7) ))
	local rf=$(( 16#$(echo "$3" | cut -b2-3) ))
	local gf=$(( 16#$(echo "$3" | cut -b4-5) ))
	local bf=$(( 16#$(echo "$3" | cut -b6-7) ))
	temp=$((rf+rz))
	r=$(bc -l <<< "scale=2; $temp*$ratio")
	temp=$((gf+gz))
	g=$(bc -l <<< "scale=2; $temp*$ratio")
	temp=$((bf+bz))
	b=$(bc -l <<< "scale=2; $temp*$ratio")
	r=$(echo "$r" | cut -f1 -d.)
	g=$(echo "$g" | cut -f1 -d.)
	b=$(echo "$b" | cut -f1 -d.)
	r=$((r-rz)); r=${r#-}
	g=$((g-gz)); g=${g#-}
	b=$((b-bz)); b=${b#-}
	# Make sure colors are in [0, 255]
	# clamp $r 0 255
	# r=$clamped
	# clamp $g 0 255
	# g=$clamped
	# clamp $b 0 255
	# b=$clamped
	color=$(printf "#%02X%02X%02X" "$r" "$g" "$b")
}

# ZERO = RED | HUNDRED = GREEN
getColor "$PERC_INT" "$START_COL" "$END_COL"
# getColor "$PERC_INT" "#FF0606" "#E609F5"


TIME="$(acpi -b | cut -d, -f3 | cut -b1-9)"

case $BLOCK_BUTTON in
	1)  if [ "$(acpi -b | grep "Discharging")" ] ; then
			notify-send "Remaining Time" "$TIME"
			DISC=""
		else
			notify-send "Time Until Charged" "$TIME"
			DISC=" "
		fi ;;
	2) ;;
	3) ;;
esac

[ "$PERC_INT" -lt 12 ] && notify-send --urgency=critical "WARNING" "LOW BATTERY!  $PERC"

echo "<span foreground='$color'>$SYMBOL $PERC</span><span foreground='#FCFC12'>$DISC</span>"
