#!/bin/bash

git init
cp ~/.config/scripts/cpp-gitignore .gitignore
mkdir src include

cp ~/.config/scripts/meson.build .

echo -e "# <++>\n" >> README.md
echo -e "#pragma once" > include/dummy.hpp
echo -e "int main()\n{\n\treturn 0;\n}\n" > src/main.cpp
cp ~/.config/scripts/MIT LICENSE

git add .gitignore src include README.md meson.build LICENSE
# git commit -am "Initial Commit"

