#!/bin/bash

git init
cp ~/.config/scripts/cpp-gitignore .gitignore
mkdir src bin include

cp ~/.config/scripts/meson.build .

echo -e "# <++>\n" >> README.md
echo -e "#pragma once\n" > include/Dummy.hpp
echo -e "int main(){return 0;}\n" > src/Main.cpp
cp ~/.config/scripts/MIT LICENSE

git add .gitignore src include README.md meson.build LICENSE
git commit -am "Initial Commit"

