#!/usr/bin/zsh

START_COL="#08FF08" # 0%
END_COL="#FF0808"	# 100%

function getColor {
	ratio="$((($1 - 24.0) / 80.0 ))";
	# Extract zero rgb and full rgb and convert to hex
	rz=$(( 16#$(echo "$2" | cut -b2-3) ))
	gz=$(( 16#$(echo "$2" | cut -b4-5) ))
	bz=$(( 16#$(echo "$2" | cut -b6-7) ))
	rf=$(( 16#$(echo "$3" | cut -b2-3) ))
	gf=$(( 16#$(echo "$3" | cut -b4-5) ))
	bf=$(( 16#$(echo "$3" | cut -b6-7) ))
	temp=$((rf + rz))
	r="$((temp * ratio))"
	temp=$((gf+gz))
	g="$((temp * ratio))"
	temp=$((bf+bz))
	b="$((temp * ratio))"
	r=$(echo "$r" | cut -f1 -d.)
	g=$(echo "$g" | cut -f1 -d.)
	b=$(echo "$b" | cut -f1 -d.)
	r=$((r-rz)); r=${r#-}
	g=$((g-gz)); g=${g#-}
	b=$((b-bz)); b=${b#-}

	color=$(printf "#%02X%02X%02X" "$r" "$g" "$b")
}

# Take a look at this, did something change?
# It used to be temp1, but now it's CPU heat?
HEAT="$(sensors | awk '/CPU:/ {print $2}' | sed -n '1p')"

getColor "$(echo $HEAT | cut -b2-5)" "$START_COL" "$END_COL"

echo "<span foreground='$color'> $HEAT</span>"

