#!/bin/bash
pgrep -i "spotify" >/dev/null || echo -n ""
NAME="$(sp eval | grep -i "TITLE" | cut -d= -f2)"
ARTIST="$(sp eval | grep -i "_ARTIST" | cut -d= -f2)"
SONG="$ARTIST - $NAME"
SONG="${SONG//\"/}"
STR_LEN=${#SONG}
if [ "$STR_LEN" -gt 27 ] ; then
	echo "$(echo "$SONG" | cut -b-27)..." | iconv -f utf8 -t ascii//TRANSLIT//IGNORE | sed 's/\&/and/g'
else
	echo "$SONG" | iconv -f utf8 -t ascii//TRANSLIT//IGNORE | sed 's/\&/and/g'
fi

case $BLOCK_BUTTON in
	1) notify-send " ${NAME//\"/}" "${ARTIST//\"/}" ;;
	2) sp play;;
	3) notify-send "Usage:" "Just Left Click To Get The Whole Song Name";;
	5) sp next && sleep 0.75 && notify-send "Playing Next Song" "$(spot-get)";;
	4) sp prev && sleep 0.75 && notify-send "Playing Previous Song" "$(spot-get)";;
esac

