#!/bin/bash
pgrep -i "spotify" >/dev/null || exit 0
# This is literraly spot-get
NAME="$(sp eval | grep -i "_TITLE" | cut -d= -f2)"
ARTIST="$(sp eval | grep -i "_ARTIST" | cut -d= -f2)"
SONG="$ARTIST - $NAME"
SONG="${SONG//\"/}"
STR_LEN="${#SONG}"
if [ "$STR_LEN" -gt 27 ] ; then
	echo " $(echo "$SONG" | cut -b-27)..." | iconv -f utf8 -t ascii//TRANSLIT//IGNORE | sed 's/\&/and/g'
else
	echo " $SONG" | iconv -f utf8 -t ascii//TRANSLIT//IGNORE | sed 's/\&/and/g'
fi

# Come up with something smarter, at least get the album name and cache the files
# Or only download when the song changes or store the URL in the filename and compare
update_album_art() {
	curl "$(sp art)" -so /tmp/album_art.jpg
}

case $BLOCK_BUTTON in
	1) update_album_art; notify-send -i /tmp/album_art.jpg " ${NAME//\"/}" "${ARTIST//\"/}";;
	2) sp play;;
	3) notify-send "Usage:" "Just Left Click To Get The Whole Song Name";;
	5) sp next && sleep 0.33 && update_album_art && notify-send -i /tmp/album_art.jpg "Playing Next Song" "$(spot-get)";;
	4) sp prev && sleep 0.33 && update_album_art && notify-send -i /tmp/album_art.jpg "Playing Previous Song" "$(spot-get)";;
esac

