#!/bin/sh

# i3lock -fni ~/Pictures/Wallpaper/Lock.png -p default -c 000000

B="#00000008"
C="#FFFFFF24"
D="#D1321CDD"
T="#D8D2F5FD"
DT="#7042B4FE"
W="#A3CE0AEF"
V="#666666FF"

i3lock -ni ~/Pictures/Wallpaper/Lock.png -p default \
	--insidever-color=$C				\
	--ringver-color=$V					\
	--insidewrong-color=$C				\
	--ringwrong-color=$W				\
	--inside-color=$B					\
	--ring-color=$D						\
	--line-color=$B						\
	--separator-color=$D				\
	--verif-color=$T					\
	--wrong-color=$T					\
	--time-color=$T						\
	--date-color=$DT					\
	--layout-color=$T					\
	--keyhl-color=$W					\
	--bshl-color=$W						\
	--indicator							\
	--clock								\
	--time-str="%H:%M:%S"				\
	--date-str="%a, %m/%Y"				\
	--greeter-text="Peki..."			\
	--greeter-pos="118:1068"			\
	--greeter-size=72					\
	--greeter-color="#C986207A"			\
	--time-size=39						\
	--date-size=25						\
	--radius=120						\
	--ring-width=12.0
