#!/bin/bash
killall dunst
dunst -config ~/.config/dunst/dunstrc &

sleep 1.2345

echo "Dunst Reloaded"

notify-send -u critical "Header" "Test message: critical test 1"
notify-send -u normal "HEADER" "Test message: normal test 2"
notify-send -u low "Test message: low test 3"
notify-send -u critical "Test message: critical test 4"
notify-send -u normal "Test message: normal test 5"
notify-send -u low "Test message: low test 6"
notify-send -u critical "<i>Italic</i>" "Test message: critical test 7"
notify-send -u normal "Test message: normal test 8"
notify-send -u low "Test message: low test 9"

