#!/usr/bin/env bash

# From https://unix.stackexchange.com/a/683668

# Output the `Dirty` section of `/proc/meminfo`
report() {
	local dirty="$(grep -w Dirty: /proc/meminfo | cut -d ':' -f 2 | tr -d ' ')"
	# Remove the kB suffix and convert to bytes
	dirty=${dirty%kB}
	echo -n -e "\e[2K\rSyncing \033[1m$(echo $((dirty*1000)) | numfmt --to=si --suffix=B)\033[m... "
}

report
# Start syncing
sync &
SYNC_PID=$!
# Give a short sleep in case there's not much
sleep 0.333
# While sync is running, report
while ps -p $SYNC_PID >/dev/null 2>&1; do
	sleep 1.75
	report
done

echo -e "\033[1;32mDone!\033[m"

