#!/usr/bin/env sh

[ -z $1 ] && cargo init && exit 0

cargo new "$1" && cd "$1" && cp ~/.config/scripts/rust-gitignore ./.gitignore
cp ~/.config/scripts/MIT ./LICENSE

cat > README.md <<EOF
# $1

## <++>

EOF

git add LICENSE Cargo.toml .gitignore src/ README.md
git commit -am "Initial Commit"

