#!/usr/bin/env sh

[ -z $1 ] && cargo init && exit 0

cargo new "$1" && cd "$1" && cp ~/.config/scripts/rust-gitignore ./.gitignore
cp ~/.config/scripts/MIT ./LICENSE

cat > README.md <<EOF
# $1

## <++>

EOF

printf "\n# [profile.release]\n# lto = true\n# codegen-units = 1\n" >> Cargo.toml

cargo build
cargo build --release

git add LICENSE Cargo.toml Cargo.lock .gitignore src/ README.md
git commit -am "Initial Commit"

