#!/usr/bin/env sh

case "$(printf "Selected Area\nCurrent Window\nFullscreen" | dmenu -l 3 -i -p "Screenshot which area?")" in
	"Selected Area") maim -u -s -m 10 "$HOME/Pictures/Screenshots/$(date '+%Y-%m-%d_%H-%M-%S').png" ;;
	"Current Window") maim -u -m 10 -i "$(xdotool getactivewindow)" "$HOME/Pictures/Screenshots/$(date '+%Y-%m-%d_%H-%M-%S').png" ;;
	"Fullscreen") maim -u -m 10 "$HOME/Pictures/Screenshots/$(date '+%Y-%m-%d_%H-%M-%S').png" ;;
esac

