#!/bin/bash
sh -c '"/home/beronthecolossus/Desktop/Code/tor-browser_en-US/Browser/start-tor-browser" --detach || ([ !  -x "/home/beronthecolossus/Desktop/Code/tor-browser_en-US/Browser/start-tor-browser" ] && "$(dirname "$*")"/Browser/start-tor-browser --detach)' dummy %k

