---
If:
  PathMatch: .*\.[ch]pp
CompileFlags:
  Add: [-xc++, -Wall, -Wextra, -Wshadow -Wconversion, -Wpedantic, -std=c++2b]

---
If:
  PathMatch: .*\.[ch]
CompileFlags:
  Add: [-xc, -Wall, -Wextra, -Wshadow -Wconversion, -Wpedantic, -std=c18]
