---
If:
  PathMatch: .*\.([hc]pp|h)
CompileFlags:
  Add: [-xc++, -Wall, -Wextra, -Wshadow -Wconversion, -Wpedantic, -std=c++2b]

---
If:
  PathMatch: .*\.c
CompileFlags:
  Add: [-xc, -Wall, -Wextra, -Wshadow -Wconversion, -Wpedantic, -std=c18]

